name: Run Tests PortalsCodingChallenge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Restore dependencies
        run: dotnet restore CodeChallengesLab.sln

      - name: Build
        run: dotnet build CodeChallengesLab.sln --configuration Release --no-restore

      - name: Run Tests with Coverage
        run: dotnet test CodeChallengesLab.sln --configuration Release --no-build --logger "console;verbosity=normal" --collect:"XPlat Code Coverage"
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/TestResults/*.trx'

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: '**/TestResults/**/coverage.cobertura.xml'

    strategy:
      fail-fast: true
